# Google Cloud Build configuration
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/whatsapp-subscription-bot:$COMMIT_SHA',
      '-t',
      'gcr.io/$PROJECT_ID/whatsapp-subscription-bot:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/whatsapp-subscription-bot:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/whatsapp-subscription-bot:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'whatsapp-subscription-bot',
      '--image', 'gcr.io/$PROJECT_ID/whatsapp-subscription-bot:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'NODE_ENV=production'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/whatsapp-subscription-bot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/whatsapp-subscription-bot:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'