apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wa-sub-bot
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/chrome-backbone-458221-m9/wa-sub-bot
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        - name: HOST
          value: 0.0.0.0
        - name: ADMIN_USER
          value: admin
        - name: ADMIN_PASS
          value: Qwe@123456
        - name: SESSION_SECRET
          value: "987654321"
        - name: FIREBASE_PROJECT_ID
          value: chrome-backbone-458221-m9
        - name: FIREBASE_CLIENT_EMAIL
          value: firebase-adminsdk@chrome-backbone-458221-m9.iam.gserviceaccount.com
        - name: FIREBASE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: firebase-private-key
              key: latest
        resources:
          limits:
            cpu: "1"
            memory: 1Gi